question_data = [
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does the term MIME stand for, in regards to computing?",
     "correct_answer": "Multipurpose Internet Mail Extensions",
     "incorrect_answers": ["Mail Internet Mail Exchange", "Multipurpose Interleave Mail Exchange",
                           "Mail Interleave Method Exchange"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "The name of technology company HP stands for what?",
     "correct_answer": "Hewlett-Packard",
     "incorrect_answers": ["Howard Packmann", "Husker-Pollosk", "Hellman-Pohl"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What was the first Android version specifically optimized for tablets?",
     "correct_answer": "Honeycomb", "incorrect_answers": ["Eclair", "Froyo", "Marshmellow"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What is the name of the default theme that is installed with Windows XP?", "correct_answer": "Luna",
     "incorrect_answers": ["Neptune", "Whistler", "Bliss"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does AD stand for in relation to Windows Operating Systems? ",
     "correct_answer": "Active Directory",
     "incorrect_answers": ["Alternative Drive", "Automated Database", "Active Department"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "The computer OEM manufacturer Clevo, known for its Sager notebook line, is based in which country?",
     "correct_answer": "Taiwan",
     "incorrect_answers": ["United States", "Germany", "China (People&#039;s Republic of)"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which programming language was developed by Sun Microsystems in 1995?", "correct_answer": "Java",
     "incorrect_answers": ["Python", "Solaris OS", "C++"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "In computing terms, typically what does CLI stand for?", "correct_answer": "Command Line Interface",
     "incorrect_answers": ["Common Language Input", "Control Line Interface", "Common Language Interface"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does &quot;LCD&quot; stand for?", "correct_answer": "Liquid Crystal Display",
     "incorrect_answers": ["Language Control Design", "Last Common Difference", "Long Continuous Design"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                       "question": "What is known as &quot;the brain&quot; of the Computer?",
                                       "correct_answer": "Central Processing Unit",
                                       "incorrect_answers": ["Motherboard", "Graphics Processing Unit", "Keyboard"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which internet company began life as an online bookstore called &#039;Cadabra&#039;?",
     "correct_answer": "Amazon", "incorrect_answers": ["eBay", "Overstock", "Shopify"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
     "correct_answer": "JavaScript", "incorrect_answers": ["C#", "Python", "PHP"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Nvidia&#039;s headquarters are based in which Silicon Valley city?", "correct_answer": "Santa Clara",
     "incorrect_answers": ["Palo Alto", "Cupertino", "Mountain View"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "While Apple was formed in California, in which western state was Microsoft founded?",
     "correct_answer": "New Mexico", "incorrect_answers": ["Washington", "Colorado", "Arizona"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does RAID stand for?", "correct_answer": "Redundant Array of Independent Disks",
     "incorrect_answers": ["Rapid Access for Indexed Devices", "Range of Applications with Identical Designs",
                           "Randomized Abstract Identification Description"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The HTML5 standard was published in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "Which of the following is a personal computer made by the Japanese company Fujitsu?",
                                      "correct_answer": "FM-7",
                                      "incorrect_answers": ["PC-9801", "Xmillennium ", "MSX"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
     "correct_answer": "C#", "incorrect_answers": ["Java", "C++", "Objective-C"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": ".at is the top-level domain for what country?", "correct_answer": "Austria",
     "incorrect_answers": ["Argentina", "Australia", "Angola"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Whistler was the codename of this Microsoft Operating System.", "correct_answer": "Windows XP",
     "incorrect_answers": ["Windows 2000", "Windows 7", "Windows 95"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "On which day did the World Wide Web go online?",
                                      "correct_answer": "December 20, 1990",
                                      "incorrect_answers": ["December 17, 1996", "November 12, 1990",
                                                            "November 24, 1995"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "How many cores does the Intel i7-6950X have?", "correct_answer": "10",
     "incorrect_answers": ["12", "8", "4"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "A Boolean value of &quot;0&quot; represents which of these words?", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "What does the term GPU stand for?",
                                      "correct_answer": "Graphics Processing Unit",
                                      "incorrect_answers": ["Gaming Processor Unit", "Graphite Producing Unit",
                                                            "Graphical Proprietary Unit"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": ".rs is the top-level domain for what country?", "correct_answer": "Serbia",
     "incorrect_answers": ["Romania", "Russia", "Rwanda"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does the &#039;S&#039; in the RSA encryption algorithm stand for?", "correct_answer": "Shamir",
     "incorrect_answers": ["Secure", "Schottky", "Stable"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Unix Time is defined as the number of seconds that have elapsed since when?",
     "correct_answer": "Midnight, January 1, 1970",
     "incorrect_answers": ["Midnight, July 4, 1976", "Midnight on the creator of Unix&#039;s birthday",
                           "Midnight, July 4, 1980"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "In programming, what do you call functions with the same name but different implementations?",
     "correct_answer": "Overloading", "incorrect_answers": ["Overriding", "Abstracting", "Inheriting"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What was the name given to Android 4.3?", "correct_answer": "Jelly Bean",
     "incorrect_answers": ["Lollipop", "Nutella", "Froyo"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "On which computer hardware device is the BIOS chip located?", "correct_answer": "Motherboard",
     "incorrect_answers": ["Hard Disk Drive", "Central Processing Unit", "Graphics Processing Unit"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What is the main CPU is the Sega Mega Drive \/ Sega Genesis?", "correct_answer": "Motorola 68000",
     "incorrect_answers": ["Zilog Z80", "Yamaha YM2612", "Intel 8088"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "The teapot often seen in many 3D modeling applications is called what?",
     "correct_answer": "Utah Teapot", "incorrect_answers": ["Pixar Teapot", "3D Teapot", "Tennessee Teapot"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Laserjet and inkjet printers are both examples of what type of printer?",
     "correct_answer": "Non-impact printer",
     "incorrect_answers": ["Impact printer", "Daisywheel printer", "Dot matrix printer"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which one of these is not an official development name for a Ubuntu release?",
     "correct_answer": "Mystic Mansion", "incorrect_answers": ["Trusty Tahr", "Utopic Unicorn", "Wily Werewolf"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                       "question": "Which of these programming languages is a low-level language?",
                                       "correct_answer": "Assembly", "incorrect_answers": ["Python", "C#", "Pascal"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which operating system was released first?", "correct_answer": "Mac OS",
     "incorrect_answers": ["Windows", "Linux", "OS\/2"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
                                      "question": "When did the online streaming service &quot;Mixer&quot; launch?",
                                      "correct_answer": "2016", "incorrect_answers": ["2013", "2009", "2011"]}]
